### ISSUE TITLE
Error: SMTP AUTH extension not supported by server

### ISSUE THREAD

**Issue by SergioFernandezCordero** [domainaware/parsedmarc#12]
HI all,

I've successfully configured parsedmarc to read reports from an email address via IMAP and registering it in our ELK cluster without issue, and I think it's a great job! But now I'm trying to configure it to send an output email, but I'm stuck in configure it using gmail account.

The version I installed using pip3 is:

```
sergiofernandez@hyperion:~$ pip3 list | grep parsedmarc
parsedmarc (3.9.7)
```

My command is (data intentionally hidden):
```
/usr/local/bin/parsedmarc -H "imap.gmail.com" -u "dmarc@example.com" -p "XXXXXXXXXXXXXX" -E https://dmarc_user:XXXXXXXX@myelk.com:9243 -O "smtp.gmail.com" -U "dmarc@example.com" -P "XXXXXXXXXXXXXXXX" -F "dmarc@example.com" -T "systems@example.com" -S "DMARC reports for example.com"
```

The report is generated but then an SMTP error appears:
```
ERROR:parsedmarc:SMTP Error: SMTP AUTH extension not supported by server
```

I've tried using the three vias to send mail using gmai as described here with no success:

https://support.google.com/a/answer/176600?hl=en

How can I solve this issue?

**Comment by seanthegeek** [comment]
Thanks for the bug report! I just fixed this in the branch for the upcoming parsedmarc 4.0 release, which will be released as soon as I finish adding Splunk support - hopefully in a week or so. 

You can install a pre-release build of parsedmarc 4.0 by running:

```bash
sudo -H pip3 install -U git+https://github.com/domainaware/parsedmarc.git@4.0
```

**Comment by SergioFernandezCordero** [comment]
Hi @seanthegeek, gave a try to 4.0 pre-release, but still the same error.

**Comment by seanthegeek** [comment]
Hmmm. I'll keep researching then. Thanks.

**Comment by seanthegeek** [comment]
Ok. I just pushed another commit.

Rerun

```bash
sudo -H pip3 install -U git+https://github.com/domainaware/parsedmarc.git@4.0
```

And let me know if that fixes it.

**Comment by SergioFernandezCordero** [comment]
Sorry but doesn't work.
I'll check the code and tell you if I can afford a solution as a pull request.

**Comment by seanthegeek** [comment]
Looking forward to it

**Comment by SergioFernandezCordero** [comment]
I've createdr PR https://github.com/domainaware/parsedmarc/pull/13 This allow you to set the port for SMTP connection and switch between SSL, STARTTLS and None, and use it properly in email_results to use it.
I've tested it against smtp.gmail.com, and seems to work. Other SMTP servers should work as well.
