### ISSUE TITLE
Current Master does not run

### ISSUE THREAD

**Issue by knightian** [domainaware/parsedmarc#277]
Even downloading fresh repo and installing it does not work.

  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/parsedmarc/cli.py", line 662, in _main
    repeat(opts.ip_db_path),
AttributeError: 'Namespace' object has no attribute 'ip_db_path'

I removed usage of ip_db_path in cli.py to get it to work, however that's not a fix as it's essentially reverting that new option you put in. But I'm not using that option so I just removed it.

**Comment by sentinel80** [comment]
The parameter ip_db_path seems to be missing from the parsedmarc.ini.

put in the [general] section the related mmdb, like
ip_db_path = /usr/share/GeoIP/GeoLite2-Country.mmdb

**Comment by seanthegeek** [comment]
This has been fixed and is included in the actual 7.1.0 release that was just published to pypi

**Comment by ashishsecdev** [comment]
@seanthegeek Wonderful and helpful utility.

I currently trying it in Windows and problem still exists, so you would have to use conf file in order to avoid the 'ip_db_path' error and also will have to open Admin CMD in order to avoid permission issue.

I am using the below command.

`parsedmarc -c parsedmarc.ini DMARC-Report-XML-.zip -o C:\`
