### ISSUE TITLE
TLS Reports from google.com are not parsed

### ISSUE THREAD

**Issue by DragonWork** [domainaware/parsedmarc#549]
### Issue

TLS Reports from **google.com** are not being parsed. The data is not being added to ElasticSearch or included in the output files (CSV or JSON). 

- **TLS reports**: Moved to the Invalid archive without any data extraction.

### Steps to Reproduce

1. Attempt to parse TLSRPT (xml.gz attachment) reports from google.com (gmail.com).
2. Observe that the reports are moved to the Invalid archive folder. There aren‘t any error logs either.

**Comment by Pascal76** [comment]
critical issue ...

**Comment by seanthegeek** [comment]
What version of parsedmarc are you running?

**Comment by DragonWork** [comment]
I'm using the latest version 8.13.0.

**Comment by arturSymbiotic** [comment]
same problem

**Comment by seanthegeek** [comment]
I've figured out that it works fine on 8.12.0 but broke in 8.13.0. I'm working on figuring out why. In the meantime, you can downgrade to 8.12.0 or keep collecting the reports in the "invalid" folder and move them back to the inbox for reprocessing after I identify and fix the problem in 8.14.1.

**Comment by seanthegeek** [comment]
Fixed in 8.14.0. Please upgrade, then move the SMTP-TLS reports from invalid to inbox for reprocessing.

**Comment by DragonWork** [comment]
> Fixed in 8.14.0. Please upgrade, then move the SMTP-TLS reports from invalid to inbox for reprocessing.

I’m sorry, but the issue still persists on 8.14.0.

**Comment by seanthegeek** [comment]
I just noticed that too. I thought I had fixed the problem because the parse_report_email function now works as expected (it didn't before), but reports are still being considered invalid when they are processed in an actual inbox. Weird. Sorry. I'll look at this more soon.

**Comment by seanthegeek** [comment]
Fixed for real in 8.14.1

**Comment by DragonWork** [comment]
You won‘t believe me, but it still doesn‘t work on 8.14.1 or 8.14.2.

**Comment by seanthegeek** [comment]
I finally figured out what the problem was, as I described in the `CHANGELOG`:

> - Fix processing of SMTP-TLS reports ([#549](https://github.com/domainaware/parsedmarc/issues/549)), which broke in commit [410663d ](https://github.com/domainaware/parsedmarc/commit/410663dbcaba019ca3d3744946348b56a635480b)(PR [#530](https://github.com/domainaware/parsedmarc/pull/530))
>   - This PR enforced a stricter check for base64-encoded strings, which SMTP TLS reports from Google did not pass
>   - Removing the check introduced its own issue, because some file paths were treated as base64-encoded strings
> - Create a separate `extract_report_from_file_path()` function for processioning reports based on a file path
> - Remove report extraction based on a file path from `extract_report()`

So, every time I'd fix one issue, the other one would pop back up. This solution is better for security too.
