### ISSUE TITLE
Failed at "raw_msg = raw_msg[msg_key]"

### ISSUE THREAD

**Issue by arnydo** [domainaware/parsedmarc#57]
Hello,

First of all, excellent tool!

However, I am unable to successfully run against a mailbox. I have installed per documentation and have everyhting working up to the actual processing of the available messages in the specified folder. Execution fails with the following:

```
> parsedmarc -c /etc/parsedmarc.ini --debug
   DEBUG:__init__.py:906:Connecting to IMAP over plain text
   DEBUG:__init__.py:829:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'MOVE', 'SPECIAL-USE']
   DEBUG:__init__.py:977:Found 3 messages in IMAP folder DMARC
   DEBUG:__init__.py:983:Processing message 1 of 3: UID 2
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/cli.py", line 404, in _main
    strip_attachment_payloads=sa
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/__init__.py", line 995, in get_dmarc_reports_from_inbox
    raw_msg = raw_msg[msg_key]
KeyError: ''
```

I am running through Davmail to connect to Exchange and have installed msgconvert.

Running against a single report stored on the local file system does parse correctly.

I have also pulled the latest dev release via Git with same result.

Fresh install of Ubuntu 16.04 LTS

Thank you for any assistance.

**Comment by seanthegeek** [comment]
Ok, I jsut pushed a change to git that will output the debugging info I need. Please upgrade from git, rerun, and post the output. I can fix this quickly.

**Comment by seanthegeek** [comment]
I just pushed a better fix to Git. Let me know if that works, and I'll release it.

**Comment by arnydo** [comment]
Quick response!

Here is the latest output:

```
parsedmarc -c /etc/parsedmarc.ini --debug
   DEBUG:__init__.py:906:Connecting to IMAP over plain text
   DEBUG:__init__.py:829:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'MOVE', 'SPECIAL-USE']
   DEBUG:__init__.py:977:Found 3 messages in IMAP folder DMARC
   DEBUG:__init__.py:983:Processing message 1 of 3: UID 2
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/cli.py", line 404, in _main
    strip_attachment_payloads=sa
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/__init__.py", line 992, in get_dmarc_reports_from_inbox
    raw_msg.keys())))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by seanthegeek** [comment]
Run the update again please

**Comment by arnydo** [comment]
Getting closer. It seems to be going through the messages now but states that they are invalid DMARC reports.

These are straight from the ESP's and the XML reports are attached to the email as a gz file. This is the expected input, correct?

```
parsedmarc -c /etc/parsedmarc.ini --debug
   DEBUG:__init__.py:906:Connecting to IMAP over plain text
   DEBUG:__init__.py:829:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'MOVE', 'SPECIAL-USE']
   DEBUG:__init__.py:977:Found 3 messages in IMAP folder DMARC
   DEBUG:__init__.py:983:Processing message 1 of 3: UID 2
 WARNING:__init__.py:1034:Message with subject "Report Domain: mydomain.cool Submitter: yahoo.com Report-ID: <1549848636.139658>" is not a valid DMARC report
   DEBUG:__init__.py:983:Processing message 2 of 3: UID 3
   ERROR:utils.py:274:More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in f 02:00:49 +0000 GMT1F for <securityadmins@mydomain.cool>; Tue, 12 Feb 2019
   ERROR:utils.py:274:More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in f 02:00:49 +0000 GMT1F for <securityadmins@mydomain.cool>; Tue, 12 Feb 2019
 WARNING:__init__.py:1034:Message with subject "Report Domain: mydomain.cool Submitter: pobox.com
 Report-ID:2019.02.11.1805030" is not a valid DMARC report
   DEBUG:__init__.py:983:Processing message 3 of 3: UID 4
 WARNING:__init__.py:1034:Message with subject "Report domain: mydomain.cool Submitter: google.com Report-ID: 2782356121887139439" is not a valid DMARC report
    INFO:cli.py:438:Watching for email - Quit with ctrl-c
   DEBUG:__init__.py:829:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'MOVE', 'SPECIAL-USE']
   ERROR:cli.py:460:IMAP error: Cannot watch inbox: IMAP server does not support the IDLE command
root@UbuntuTemplate:/home/notroot# parsedmarc -c /etc/parsedmarc.ini --debug
   DEBUG:__init__.py:906:Connecting to IMAP over plain text
   DEBUG:__init__.py:829:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'MOVE', 'SPECIAL-USE']
   DEBUG:__init__.py:977:Found 4 messages in IMAP folder DMARC
   DEBUG:__init__.py:983:Processing message 1 of 4: UID 2
 WARNING:__init__.py:1034:Message with subject "Report Domain: mydomain.cool Submitter: yahoo.com Report-ID: <1549848636.139658>" is not a valid DMARC report
   DEBUG:__init__.py:983:Processing message 2 of 4: UID 3
   ERROR:utils.py:274:More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in f 02:00:49 +0000 GMT1F for <securityadmins@mydomain.cool>; Tue, 12 Feb 2019
   ERROR:utils.py:274:More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in f 02:00:49 +0000 GMT1F for <securityadmins@mydomain.cool>; Tue, 12 Feb 2019
 WARNING:__init__.py:1034:Message with subject "Report Domain: mydomain.cool Submitter: pobox.com
 Report-ID:2019.02.11.1805030" is not a valid DMARC report
   DEBUG:__init__.py:983:Processing message 3 of 4: UID 4
 WARNING:__init__.py:1034:Message with subject "Report domain: mydomain.cool Submitter: google.com Report-ID: 2782356121887139439" is not a valid DMARC report
   DEBUG:__init__.py:983:Processing message 4 of 4: UID 5
   ERROR:utils.py:274:More than one match found for (?:with(?! cipher)\s+(?P<with>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+id|\s+for|\s+via|;)) in 23:30:43 +0000 GMT3F for <securityadmins@mydomain.cool>; Mon, 11 Feb 2019
   ERROR:utils.py:274:More than one match found for (?:with(?! cipher)\s+(?P<with>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+id|\s+for|\s+via|;)) in 23:30:43 +0000 GMT3F for <securityadmins@mydomain.cool>; Mon, 11 Feb 2019
 WARNING:__init__.py:1034:Message with subject "Dmarc Aggregate Report Domain: {mydomain.cool}  Submitter:
 {Amazon SES}  Date: {2019-02-10}  Report-ID:
 {bebe82eb-e4c4-496f-b35b-4b908c632b5f}" is not a valid DMARC report
    INFO:cli.py:438:Watching for email - Quit with ctrl-c
   DEBUG:__init__.py:829:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'MOVE', 'SPECIAL-USE']
   ERROR:cli.py:460:IMAP error: Cannot watch inbox: IMAP server does not support the IDLE command
```

**Comment by seanthegeek** [comment]
Please provide the A copy of the email from davmail by dragging it from the inbox of a IMAP mail client to your desktop, then into the comment box.

**Comment by arnydo** [comment]
Do you have a DM option rather than posting full email info in public issue board?

**Comment by seanthegeek** [comment]
You can email the .eml file to me at seanthegeek@pm[.]me

**Comment by arnydo** [comment]
Just sent your way.

**Comment by seanthegeek** [comment]
Fixed in 6.1.0

**Comment by arnydo** [comment]
Perfect! Worked like a charm.

Thank you very much for the prompt assistance and resolution to the issue!

**Comment by arnydo** [comment]
Still not completely out of the woods...
Running against all of our reports we have gathered and ran into another error:
```
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/cli.py", line 404, in _main
    strip_attachment_payloads=sa
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/__init__.py", line 987, in get_dmarc_reports_from_inbox
    ["RFC822"])[msg_uid]
KeyError: 115
```

May I propose a feature...allow program to skip failed items, log the error, and continue processing? 

Is there a way to find out which msg it failed on?

**Comment by arnydo** [comment]
Looks like it may have been a timeout issue with Davmail.
Changed ClientSoTimeout to 0 and it processed all.

```
# client connection timeout in seconds - default 300, 0 to disable
davmail.clientSoTimeout=0
```

Completed all reports.

**Comment by seanthegeek** [comment]
Thanks. I just added that to the documentation. 

Also, I noticed this error in your logs:

>  IMAP server does not support the IDLE command

Make sure you enable IDLE in webdav too, so it can poll for new messages

```ini
# Enable IDLE support, set polling delay in minutes
   davmail.imapIdleDelay=1
```

The full recommended config is at https://domainaware.github.io/parsedmarc/#accessing-an-inbox-using-owa-ews 
```

**Comment by sergihv** [comment]
Hello Seam,
Seems like I have same issue 
WARNING:__init__.py:1093:Message with subject "DMARC Forensic Report for mydomain.com from IP xxxxx" is not a valid DMARC report

WARNING:__init__.py:1093:Message with subject "DMARC Forensic Report for mydomain.com from IP xxxxxx" is not a valid DMARC report

WARNING:__init__.py:1093:Message with subject "DMARC Forensic Report for mydomain.com from IP xxxxxx" is not a valid DMARC report

And repeats over and over again and get no data from my dmarc inbox.
Could you help me with this?
